export const SET_USER = "SET_USER";
export const SET_LOADING = "SET_LOADING";
export const SET_NAVBAR = "SET_NAVBAR";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const BRING_ALL_USERS = "BRING_ALL_USERS";
export const BRING_ALL_LIBRARY_ITEMS = "BRING_ALL_LIBRARY_ITEMS";
export const BRING_MY_ITEMS = "BRING_MY_ITEMS";
export const BRING_ALL_AVAILABLE_AND_HOLDED_ITEMS_FOR_LEND =
    "BRING_ALL_AVAILABLE_AND_HOLDED_ITEMS_FOR_LEND";
export const BRING_ALL_RETURNABLE_ITEMS = "BRING_ALL_RETURNABLE_ITEMS";
export const BRING_WARNINGS = "BRING_WARNINGS";
export const BRING_ALL_COURSES = "BRING_ALL_COURSES";
export const BRING_MY_COURSES = "BRING_MY_COURSES";
export const BRING_STUDENTS_FOR_THE_CHOOSEN_COURSE =
    "BRING_STUDENTS_FOR_THE_CHOOSEN_COURSE";

export const BRING_ASSIGNED_LIBRARY_ITEMS = "BRING_ASSIGNED_LIBRARY_ITEMS";
export const BRING_REPORTS = "BRING_REPORTS";
