export const SET_USER = "SET_USER";
export const SET_STUDENT = "SET_STUDENT";
export const SET_USER_TYPE = "SET_USER_TYPE";
export const SET_LOADING = "SET_LOADING";
export const SET_NAVBAR = "SET_NAVBAR";

export const BRING_SPORT_ACTIVITIES = "BRING_SPORT_ACTIVITIES";
export const BRING_BRING_SPORT_ACTIVITIES_LEFT_CAPACITIES =
    "BRING_BRING_SPORT_ACTIVITIES_LEFT_CAPACITIES";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";

export const RESERVE_SERVER_RESPONSE_MSG = "RESERVE_SERVER_RESPONSE_MSG";
export const MY_RESERVATIONS = "MY_RESERVATIONS";
export const CANCEL_RESERVATION_SERVER_RESPONSE_MSG =
    "CANCEL_RESERVATION_SERVER_RESPONSE_MSG";
